### ISSUE TITLE
`make` command not available

### ISSUE THREAD

**Issue by alfureu** [bjuretko/docker-baikal-infcloud#22]
I cannot run `make` on my NAS (asustor) as I do not have any. Therefore the following command does not build the docker:

> To build the Docker image just call
>> `make`

Before, you had the following command listed as well:

> `build --tag "alpine-infcloud-baikal:3.5-0.13.1-0.4.6" --tag "alpine-infcloud-baikal:latest" .`

Why did you delete it? It was the only method to build the docker image for me.

**Comment by alfureu** [comment]
sorry, I found the command, however, even if I download entware and try to use make, it ends with an error

**Comment by bjuretko** [comment]
see the content of `Makefile` if you want to run them manually
