### ISSUE TITLE
Ignoring APKINDEX error

### ISSUE THREAD

**Issue by alfureu** [bjuretko/docker-baikal-infcloud#23]
I am getting a strange errorn while building (see attached screenshot)

![image](https://user-images.githubusercontent.com/10846169/57168503-451c8e00-6e02-11e9-927f-c0c040a8856c.png)

**Comment by bjuretko** [comment]
I improved the Dockerfile regarding the use of `apk --no-cache` which includes a package update without cache. It is in the master branch.

**Comment by alfureu** [comment]
The funny thing is that I was using it while building. Still appeared. Will keep an eye out next time I build it. Now it is working, so will not redo everything from scratch.
