### ISSUE TITLE
Is there a way to mount the config file of infcloud 

### ISSUE THREAD

**Issue by BobWs** [bjuretko/docker-baikal-infcloud#24]
Hi how do a mount the infloud config.js file with a docker folder? 
I have already tried this ` -v /baikal-data/infcloud-config:/var/www/infcloud/config `
But it didn’t work

**Comment by bjuretko** [comment]
See https://github.com/bjuretko/docker-baikal-infcloud/blob/master/docker-compose.yml#L11

**Comment by BobWs** [comment]
okay thank I will give it a try

**Comment by BobWs** [comment]
unfortunately mounting the infcloud config file isn't working. when I mount the file I can't connect to infcloud. When I remove the mount then infcloud can connect. (See screenshot how I mounted the file in Synology docker) Do you have any other suggestions ?

![Screen Shot 2019-05-11 at 19 15 36](https://user-images.githubusercontent.com/5485820/57573003-655fd480-7422-11e9-8ce8-ce0f0c8839d2.png)

**Comment by bjuretko** [comment]
Is the config correct and loaded correctly? Did you clear the cache in the browser?
Otherwise drop your config here and the error message.

**Comment by BobWs** [comment]
Could you maybe write some kind of tutorial how to mount the config file for infcloud on the Synology section. And where can I find the config file to mount?

**Comment by bjuretko** [comment]
Your screenshot looks correct, maybe use absolute pathes for File/folder ?

**Comment by bjuretko** [comment]
I wrote stuff about synology here https://github.com/bjuretko/docker-baikal-infcloud/blob/master/synology.md
