### ISSUE TITLE
Linking with host MySQL

### ISSUE THREAD

**Issue by alfureu** [bjuretko/docker-baikal-infcloud#27]
I try to link this with my already existing host MySQL database. However, whenever I try to bind the volume `/usr/builtin/var/lib/mysql:/var/lib/mysql`, I get the following error on the admin page:

```
Exception: Fatal error: no connection to a database is available. in /var/www/baikal/Core/Frameworks/Baikal/Core/Tools.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Framework.php(80): Baikal\Core\Tools::assertBaikalIsOk()
#1 /var/www/baikal/Core/Frameworks/BaikalAdmin/Framework.php(35): Baikal\Framework::bootstrap()
#2 /var/www/baikal/html/admin/index.php(53): BaikalAdmin\Framework::bootstrap()
#3 {main}
```

**Comment by bjuretko** [comment]
Parallel access on data files is not a good idea ... if your host's mysql instance exposed on the same network as the container, you could access it directly via localhost.
